// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnnjutovpnonltbzcmqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubmp1dG92cG5vbmx0YnpjbXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzkwNjEsImV4cCI6MjA2OTk1NTA2MX0.pcHrppt8UYjHVkkAuf9X6k9ZM-N5PcdtJWkVI3c00ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});